# Generated by Django 5.2.17 on 2026-09-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_perfil_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("data_nascimento", models.DateField()),
                ("endereco", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="alunos/fotos/"),
                ),
                ("contato_emergencia_nome", models.CharField(max_length=150)),
                ("contato_emergencia_telefone", models.CharField(max_length=15)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "perfil",
                    models.OneToOneField(
                        limit_choices_to={"tipo": "aluno"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno",
                        to="accounts.perfil",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
