# Generated by Django 5.2.17 on 2026-09-12 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="contato_emergencia_telefone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 números (com DDD), sem espaços ou traços.",
                        regex="^\\d{10,11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter exatamente 11 números, sem pontos ou traços.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 números (com DDD), sem espaços ou traços.",
                        regex="^\\d{10,11}$",
                    )
                ],
            ),
        ),
    ]
