# Generated by Django 5.2.17 on 2026-09-12 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0003_alter_aluno_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefone deve conter 10 ou 11 números (com DDD), sem espaços ou traços.",
                        regex="^\\d{10,11}$",
                    )
                ],
            ),
        ),
    ]
