# Generated by Django 5.2.17 on 2026-09-12 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricoes_medicas', models.TextField(blank=True, help_text='Problemas cardíacos, respiratórios, restrições articulares, etc.', null=True, verbose_name='Restrições Médicas')),
                ('historico_lesoes', models.TextField(blank=True, help_text='Fraturas, luxações, entorses, cirurgias ortopédicas prévias.', null=True, verbose_name='Histórico de Lesões')),
                ('condicoes_cronicas', models.TextField(blank=True, help_text='Hipertensão, diabetes, asma ou uso contínuo de medicação.', null=True, verbose_name='Condições Crônicas')),
                ('autorizacao_atividade_fisica', models.BooleanField(default=False, help_text='Declaração de aptidão e autorização para os treinos na academia.', verbose_name='Autorização para prática de atividade física')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='alunos.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
    ]
