# Generated by Django 5.2.17 on 2026-09-19 15:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao_modalidades', models.TextField(help_text='Ex: Musculação, Dança, Pilates', verbose_name='Modalidades Incluídas')),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Periodicidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Mensalidade (R$)')),
                ('fidelidade_meses', models.PositiveIntegerField(default=0, help_text='0 se não houver fidelidade', verbose_name='Período de Fidelidade (meses)')),
                ('multa_cancelamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Multa por Cancelamento Antecipado (%)')),
                ('taxa_adesao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taxa de Adesão (R$)')),
                ('dia_vencimento', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia Padrão de Vencimento')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar este plano de novas matrículas.', verbose_name='Plano Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['nome'],
            },
        ),
    ]
