# Generated by Django 5.2.17 on 2026-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='descricao_modalidades',
            new_name='modalidades_incluidas',
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, help_text='Resumo ou condições gerais do plano.', null=True, verbose_name='Descrição do Plano'),
        ),
    ]
