# Generated by Django 5.2.17 on 2026-09-20 05:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financeiro",
            "0002_rename_descricao_modalidades_plano_modalidades_incluidas_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoRegraFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("dias_tolerancia", "Dias de tolerância"),
                            ("juros_diario", "Juros por dia de atraso (%)"),
                            ("multa_atraso", "Multa por atraso (%)"),
                            ("dias_bloqueio", "Dias de atraso que bloqueiam o acesso"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valor_anterior", models.CharField(max_length=20)),
                ("valor_novo", models.CharField(max_length=20)),
                ("alterado_por_nome", models.CharField(max_length=150)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de regra financeira",
                "verbose_name_plural": "Histórico das regras financeiras",
                "ordering": ["-alterado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RegraFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_tolerancia",
                    models.PositiveIntegerField(
                        help_text="Dias após o vencimento antes de considerar o aluno inadimplente.",
                        validators=[django.core.validators.MaxValueValidator(365)],
                        verbose_name="Dias de tolerância",
                    ),
                ),
                (
                    "juros_diario",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Percentual cobrado por cada dia de atraso. Ex: 0,033",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Juros por dia de atraso (%)",
                    ),
                ),
                (
                    "multa_atraso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentual único cobrado quando o pagamento atrasa. Ex: 2,00",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Multa por atraso (%)",
                    ),
                ),
                (
                    "dias_bloqueio",
                    models.PositiveIntegerField(
                        help_text="A partir de quantos dias de atraso a entrada do aluno é bloqueada.",
                        validators=[django.core.validators.MaxValueValidator(365)],
                        verbose_name="Dias de atraso que bloqueiam o acesso",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra financeira",
                "verbose_name_plural": "Regras financeiras",
            },
        ),
    ]
