# Generated by Django 5.2.17 on 2026-09-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_anamnese'),
        ('financeiro', '0003_historicoregrafinanceira_regrafinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('pix', 'PIX'), ('boleto', 'Boleto Bancário'), ('dinheiro', 'Dinheiro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(default='ATIVA', max_length=20, verbose_name='Status da Matrícula')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.aluno', verbose_name='Aluno')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adesao', 'Taxa de Adesão'), ('mensalidade', 'Mensalidade')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor (R$)')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('competencia', models.CharField(blank=True, max_length=7, null=True, verbose_name='Competência (AAAA-MM)')),
                ('paga', models.BooleanField(default=False, verbose_name='Paga?')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='financeiro.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'mensalidade')), fields=('matricula', 'competencia'), name='uq_matricula_competencia_mensalidade')],
            },
        ),
    ]
