# Generated by Django 6.1.1 on 2026-09-19 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terca'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=7)),
                ('horario', models.TimeField()),
                ('sala', models.CharField(max_length=50)),
                ('capacidade_maxima', models.PositiveBigIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='turmas.modalidade')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil__tipo': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
